name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
  - title: 'Documentation'
    label: 'documentation'
  - title: 'CI'
    label: 'ci'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'ci'
      - 'bug'
      - 'documentation'
  default: patch
change-template: '- $TITLE, by @$AUTHOR (#$NUMBER)'
template: |
  # What's changed

  $CHANGES
