name: Release drafter

on:
  push:
    branches:
      - main
      - master

  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled

permissions:
  contents: write
  pull-requests: read

jobs:
  release-drafter:
    runs-on: ubuntu-24.04
    steps:
      - uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5 # v6.1.0
        with:
          config-name: RELEASE_DRAFTER.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
